version: '2'

services:
  zookeeper:
    container_name: goctupus_zookeeper
    ports:
      - "2181:2181"
    image: zookeeper

  kafka:
    container_name: goctupus_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    image: goctopus/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafkaconsumer:
    container_name: goctupus_kafka_consumer
    depends_on:
      - kafka
    image: goctopus/kafka/consumer
    environment:
      KAFKA_PORT_9092_TCP_ADDR: kafka
      KAFKA_PORT_9092_TCP_PORT: 9092
      MONGO_PORT_27017_TCP_ADDR: mongo
      MONGO_PORT_27017_TCP_PORT: 27017

  kafkaproducer:
    container_name: goctupus_kafka_producer
    depends_on:
      - kafka
      - kafkaconsumer
    image: goctopus/kafka/producer
    environment:
      KAFKA_PORT_9092_TCP_ADDR: kafka
      KAFKA_PORT_9092_TCP_PORT: 9092

  mongo:
    container_name: goctupus_mongo
    ports:
      - "27017:27017"
    image: goctopus/mongo

  nats:
      container_name: goctupus_nats
      ports:
        - "4222:4222"
      image: goctopus/nats
